name: alfheim

include:
  - ./infrastructure/compose.yml
  - ./infrastructure/caddy/compose.yml
  - ./core/dashboard/compose.yml
  - ./infrastructure/telemetry/compose.yml
  - ./apps/maintenance/compose.yml
  - ./apps/pantry/compose.yml
  - ./apps/shopping/compose.yml
  - ./apps/chores/compose.yml
  - ./apps/chat/compose.yml
  - ./apps/workout/compose.yml

networks:
  gateway-net:
    name: gateway-net
    external: true
  infra-net:
    name: infra-net
    external: true
  core-net:
    name: core-net
    external: true
  app-pantry-net:
    name: app-pantry-net
    external: true
  app-shopping-net:
    name: app-shopping-net
    external: true
  app-chores-net:
    name: app-chores-net
    external: true
  app-maintenance-net:
    name: app-maintenance-net
    external: true
  app-chat-net:
    name: app-chat-net
    external: true
  app-workout-net:
    name: app-workout-net
    external: true
  observability-internal:
    name: observability-internal
    external: true
