name: alfheim

include:
  - ./infrastructure/compose.yml
  - ./infrastructure/caddy/compose.yml
  - ./apps/dashboard/compose.yml
  - ./apps/logging-stack/compose.yml
  - ./apps/maintenance/compose.yml
  - ./apps/pantry/compose.yml
  - ./apps/shopping/compose.yml
  - ./apps/chores/compose.yml

networks:
  public-ingress:
    name: public-ingress
    driver: bridge
  pantry-internal:
    name: pantry-internal
    driver: bridge
  shopping-internal:
    name: shopping-internal
    driver: bridge
  chores-internal:
    name: chores-internal
    driver: bridge
  observability-internal:
    name: observability-internal
    external: true
