"use client";

import { useState, useRef } from "react";
import { useTranslation } from "@alfheim/shared";
import { X, Search, Loader2, CheckCircle2, AlertCircle } from "lucide-react";
import { ModelBlockVisibilitySelector } from "./ModelBlockVisibilitySelector";
import { useDiscoverModels } from "../services/modelBlockService";
import type { CreateModelBlockRequest, ModelBlock, UpdateModelBlockRequest } from "../types";

function formatModelDisplayName(tag: string): string {
  if (!tag) return "";
  const clean = tag.replace(/:latest$/, "");
  const parts = clean.split(/[:\-_]/);
  return parts
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(" ");
}

interface ModelBlockFormModalProps {
  model?: ModelBlock | null;
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (payload: CreateModelBlockRequest | { id: string; payload: UpdateModelBlockRequest }) => void;
  isPending: boolean;
}

export function ModelBlockFormModal({
  model,
  isOpen,
  onClose,
  onSubmit,
  isPending,
}: ModelBlockFormModalProps) {
  const { t } = useTranslation();
  const isEditing = !!model;

  const [displayName, setDisplayName] = useState(model?.display_name ?? "");
  const [providerType, setProviderType] = useState(model?.provider_type ?? "ollama");
  const [modelIdentifier, setModelIdentifier] = useState(model?.model_identifier ?? "");
  const [baseUrl, setBaseUrl] = useState(model?.base_url ?? "");
  const [apiKey, setApiKey] = useState("");
  const [visibility, setVisibility] = useState<"private" | "shared">(model?.visibility ?? "private");

  // Discovery state
  const discoverMutation = useDiscoverModels();
  const [discoveredModels, setDiscoveredModels] = useState<string[]>([]);
  const [isManualModel, setIsManualModel] = useState(false);
  const [discoverStatus, setDiscoverStatus] = useState<"idle" | "success" | "error">("idle");
  const [discoverMessage, setDiscoverMessage] = useState("");
  const autoGeneratedNameRef = useRef<string>("");

  if (!isOpen) return null;

  const handleDiscover = () => {
    setDiscoverStatus("idle");
    setDiscoverMessage("");
    discoverMutation.mutate(
      {
        provider_type: providerType,
        base_url: baseUrl || undefined,
        api_key: apiKey || undefined,
      },
      {
        onSuccess: (data) => {
          if (data.models && data.models.length > 0) {
            setDiscoveredModels(data.models);
            setIsManualModel(false);
            setDiscoverStatus("success");
            setDiscoverMessage(t("Chat.scanSuccess", { count: data.models.length }));

            // If identifier was empty or not in list, pre-select the first model
            if (!modelIdentifier || !data.models.includes(modelIdentifier)) {
              const firstModel = data.models[0];
              setModelIdentifier(firstModel);
              if (!displayName || displayName === autoGeneratedNameRef.current) {
                const autoName = formatModelDisplayName(firstModel);
                setDisplayName(autoName);
                autoGeneratedNameRef.current = autoName;
              }
            }
          } else {
            setDiscoveredModels([]);
            setDiscoverStatus("error");
            setDiscoverMessage(t("Chat.scanError"));
          }
        },
        onError: () => {
          setDiscoveredModels([]);
          setDiscoverStatus("error");
          setDiscoverMessage(t("Chat.scanError"));
        },
      }
    );
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (isEditing && model) {
      onSubmit({
        id: model.id,
        payload: {
          display_name: displayName,
          model_identifier: modelIdentifier,
          base_url: baseUrl || undefined,
          api_key: apiKey || undefined,
          visibility,
        },
      });
    } else {
      onSubmit({
        display_name: displayName,
        provider_type: providerType,
        model_identifier: modelIdentifier,
        base_url: baseUrl || undefined,
        api_key: apiKey || undefined,
        visibility,
      });
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="w-full max-w-lg rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-card)] p-6 shadow-2xl space-y-4">
        <div className="flex items-center justify-between border-b border-[var(--border-subtle)] pb-3">
          <h2 className="text-lg font-bold text-[var(--text-main)]">
            {isEditing ? t("Chat.editModelBlock") : t("Chat.addModelBlock")}
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label={t("Chat.close")}
            className="p-1 rounded text-[var(--text-muted)] hover:text-[var(--text-main)] cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-3.5">
          {!isEditing && (
            <div>
              <label className="block text-xs font-semibold text-[var(--text-muted)] mb-1">
                {t("Chat.modelProvider")}
              </label>
              <select
                value={providerType}
                onChange={(e) => {
                  setProviderType(e.target.value);
                  setDiscoveredModels([]);
                  setDiscoverStatus("idle");
                }}
                className="w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none"
              >
                <option value="ollama">Ollama (Local / Self-hosted)</option>
                <option value="openai_compatible">OpenAI Compatible / vLLM</option>
                <option value="openrouter">OpenRouter</option>
                <option value="anthropic">Anthropic Claude</option>
                <option value="gemini">Google Gemini</option>
              </select>
            </div>
          )}

          <div>
            <label className="block text-xs font-semibold text-[var(--text-muted)] mb-1">
              {t("Chat.modelBaseUrl")}
            </label>
            {providerType === "ollama" ? (
              <div className="space-y-1.5">
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={baseUrl}
                    onChange={(e) => setBaseUrl(e.target.value)}
                    className="flex-1 min-w-0 rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none font-mono"
                    placeholder="http://host.docker.internal:11434"
                  />
                  <button
                    type="button"
                    disabled={discoverMutation.isPending}
                    onClick={handleDiscover}
                    className="px-3 py-2 rounded-lg bg-[var(--surface-elevated)] hover:bg-[var(--surface-canvas)] border border-[var(--border-subtle)] hover:border-[var(--primary-main)]/60 text-xs font-semibold text-[var(--text-main)] flex items-center gap-1.5 transition-colors cursor-pointer disabled:opacity-50 shrink-0"
                  >
                    {discoverMutation.isPending ? (
                      <Loader2 className="w-3.5 h-3.5 animate-spin text-[var(--primary-main)]" />
                    ) : (
                      <Search className="w-3.5 h-3.5 text-[var(--primary-main)]" />
                    )}
                    <span>
                      {discoverMutation.isPending
                        ? t("Chat.scanningModels")
                        : t("Chat.scanModels")}
                    </span>
                  </button>
                </div>
                {discoverStatus === "success" && (
                  <p className="text-[11px] font-mono text-emerald-400 flex items-center gap-1">
                    <CheckCircle2 className="w-3 h-3 shrink-0" />
                    <span>{discoverMessage}</span>
                  </p>
                )}
                {discoverStatus === "error" && (
                  <p className="text-[11px] font-mono text-amber-400 flex items-center gap-1">
                    <AlertCircle className="w-3 h-3 shrink-0" />
                    <span>{discoverMessage}</span>
                  </p>
                )}
              </div>
            ) : (
              <input
                type="text"
                value={baseUrl}
                onChange={(e) => setBaseUrl(e.target.value)}
                className="w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none font-mono"
                placeholder="http://ollama:11434 oder https://api.openai.com/v1"
              />
            )}
          </div>

          <div>
            <div className="flex items-center justify-between mb-1">
              <label className="block text-xs font-semibold text-[var(--text-muted)]">
                {t("Chat.modelIdentifier")}
              </label>
              {discoveredModels.length > 0 && isManualModel && (
                <button
                  type="button"
                  onClick={() => setIsManualModel(false)}
                  className="text-[11px] text-[var(--primary-main)] hover:underline cursor-pointer"
                >
                  {t("Chat.selectDiscoveredModel")}
                </button>
              )}
            </div>

            {discoveredModels.length > 0 && !isManualModel ? (
              <select
                value={modelIdentifier}
                onChange={(e) => {
                  const val = e.target.value;
                  if (val === "__custom__") {
                    setIsManualModel(true);
                    setModelIdentifier("");
                  } else {
                    setModelIdentifier(val);
                    if (val && (!displayName || displayName === autoGeneratedNameRef.current)) {
                      const autoName = formatModelDisplayName(val);
                      setDisplayName(autoName);
                      autoGeneratedNameRef.current = autoName;
                    }
                  }
                }}
                className="w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none"
              >
                <option value="">{t("Chat.selectDiscoveredModel")}</option>
                {discoveredModels.map((m) => (
                  <option key={m} value={m}>
                    {m}
                  </option>
                ))}
                <option value="__custom__">{t("Chat.manualModelInput")}</option>
              </select>
            ) : (
              <input
                type="text"
                required
                value={modelIdentifier}
                onChange={(e) => setModelIdentifier(e.target.value)}
                className="w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none"
                placeholder="z. B. llama3.1:8b, gemma2:9b, gpt-4o"
              />
            )}
          </div>

          <div>
            <label className="block text-xs font-semibold text-[var(--text-muted)] mb-1">
              {t("Chat.modelDisplayName")}
            </label>
            <input
              type="text"
              required
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              className="w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none"
              placeholder="z. B. Gemma 2 9B oder Local Llama"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-[var(--text-muted)] mb-1">
              {t("Chat.modelApiKey")}
            </label>
            <input
              type="password"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              className="w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-canvas)] px-3 py-2 text-sm text-[var(--text-main)] focus:border-[var(--primary-main)] outline-none font-mono"
              placeholder={isEditing ? "(Unverändert lassen)" : "sk-... (optional für Ollama)"}
            />
          </div>

          <ModelBlockVisibilitySelector
            value={visibility}
            onChange={setVisibility}
            disabled={isPending}
          />

          <div className="pt-3 border-t border-[var(--border-subtle)] flex items-center justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-lg text-xs font-semibold border border-[var(--border-subtle)] text-[var(--text-muted)] hover:text-[var(--text-main)] cursor-pointer"
            >
              {t("Chat.cancel")}
            </button>
            <button
              type="submit"
              disabled={isPending}
              className="px-4 py-2 rounded-lg text-xs font-semibold bg-[var(--primary-main)] text-black cursor-pointer disabled:opacity-50"
            >
              {t("Chat.save")}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
