#!/usr/bin/env bash
# =============================================================================
# scripts/zitadel-bootstrap.sh — provision Zitadel OIDC clients for local dev
#
# The IAM this replaced (see ADR 0003) shipped an admin CLI inside its own
# container, so the old bootstrap could `docker exec` a client registration.
# Zitadel has no such CLI: everything goes through its Management API, which
# needs a bearer token. The token comes from the "first instance" machine user
# that infrastructure/compose.yml asks Zitadel to create, whose personal access
# token (PAT) Zitadel writes to a host-mounted file
# (ZITADEL_FIRSTINSTANCE_PATPATH).
#
# The second difference that matters: a Zitadel OIDC application's client ID is
# generated by Zitadel and cannot be chosen, and the client secret is returned
# exactly once — at creation or on an explicit regenerate. So this script does
# not "declare" a client the way a realm export used to; it reconciles one and
# writes the resulting credentials back into the root .env, from where
# infrastructure/telemetry/compose.yml feeds them to Grafana.
#
# Usage:
#   ./scripts/zitadel-bootstrap.sh            # reconcile, reuse existing secrets
#   ./scripts/zitadel-bootstrap.sh --force    # always regenerate the secret
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Colour helpers (kept identical to up.sh so nested output looks uniform)
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
DIM='\033[2m'
RESET='\033[0m'

ok()   { echo -e "${GREEN}✔${RESET}  $*"; }
info() { echo -e "${CYAN}▶${RESET}  $*"; }
warn() { echo -e "${YELLOW}⚠${RESET}  $*"; }
fail() { echo -e "${RED}✖${RESET}  $*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
PAT_FILE="${REPO_ROOT}/infrastructure/zitadel/machinekey/pat.txt"

FORCE_SECRET=false
for arg in "$@"; do
  case "$arg" in
    --force) FORCE_SECRET=true ;;
    -h|--help)
      sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) warn "Unknown argument: $arg" ;;
  esac
done

# ---------------------------------------------------------------------------
# Configuration — derived from .env so a re-pointed dev domain keeps working
# ---------------------------------------------------------------------------
env_value() {
  local key="$1" default="${2:-}" line=""
  [[ -f "${ENV_FILE}" ]] || { echo "${default}"; return; }
  line=$(grep -E "^${key}=" "${ENV_FILE}" | tail -n 1 || true)
  [[ -z "${line}" ]] && { echo "${default}"; return; }
  line="${line#*=}"
  # Strip optional surrounding quotes written by init-env.sh.
  line="${line%\"}"; line="${line#\"}"
  line="${line%\'}"; line="${line#\'}"
  echo "${line}"
}

[[ -f "${ENV_FILE}" ]] || fail "No .env at ${ENV_FILE}. Run ./scripts/init-env.sh --auto first."

AUTH_HOST="$(env_value ZITADEL_EXTERNALDOMAIN auth.alfheim.loegien.localhost)"
APP_HOST="$(env_value ALFHEIM_HOST alfheim.loegien.localhost)"

# Zitadel resolves the instance from the Host header, so every API call is made
# against the container on infra-net while claiming the external domain. That
# keeps this script independent of Caddy and of host DNS for *.localhost.
ZITADEL_INTERNAL="http://zitadel:8080"
CURL_IMAGE="curlimages/curl:8.11.1"

PROJECT_NAME="Alfheim"
GRAFANA_APP_NAME="Grafana"

# ---------------------------------------------------------------------------
# api — one Management/Admin API call, executed from a throwaway container on
# infra-net. Prints the response body; fails the script on a non-2xx status.
#
#   $1 — HTTP method
#   $2 — path (e.g. /management/v1/projects)
#   $3 — JSON body (optional)
#   $4 — a Zitadel error id to treat as success (optional)
# ---------------------------------------------------------------------------
api() {
  local method="$1" path="$2" body="${3:-}" tolerate="${4:-}"
  local response="" status=""

  local args=(
    --silent --show-error
    --write-out '\n%{http_code}'
    --request "${method}"
    --header "Host: ${AUTH_HOST}"
    --header "Authorization: Bearer ${ZITADEL_PAT}"
    --header "Content-Type: application/json"
  )
  [[ -n "${body}" ]] && args+=(--data "${body}")
  args+=("${ZITADEL_INTERNAL}${path}")

  response=$(docker run --rm --network infra-net "${CURL_IMAGE}" "${args[@]}" 2>&1) || {
    fail "Zitadel API call ${method} ${path} could not be executed:
${response}"
  }

  status="${response##*$'\n'}"
  response="${response%$'\n'*}"

  if [[ ! "${status}" =~ ^2 ]]; then
    if [[ -n "${tolerate}" && "${response}" == *"${tolerate}"* ]]; then
      return 0
    fi
    fail "Zitadel API ${method} ${path} returned HTTP ${status}:
${response}"
  fi
  printf '%s' "${response}"
}

# ---------------------------------------------------------------------------
# json_field — pull a top-level-ish string value out of a JSON document.
# Zitadel's responses are flat enough that this beats adding a jq dependency
# to a script whose whole job is to run before the stack is up.
# ---------------------------------------------------------------------------
json_field() {
  local key="$1" match=""
  # `grep` exits 1 on no match, which under `set -o pipefail` would abort the
  # whole script; an absent field is a normal "not provisioned yet" answer.
  match=$(grep -o "\"${key}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -n 1 || true)
  [[ -z "${match}" ]] && return 0
  printf '%s' "${match}" | sed -e "s/.*:[[:space:]]*\"//" -e 's/"$//'
}

# ---------------------------------------------------------------------------
# set_env — idempotently write KEY=value into the root .env
# ---------------------------------------------------------------------------
set_env() {
  local key="$1" value="$2"
  [[ -f "${ENV_FILE}" ]] || fail "No .env at ${ENV_FILE}. Run ./scripts/init-env.sh first."

  if ! grep -qE "^${key}=" "${ENV_FILE}"; then
    printf '%s=%s\n' "${key}" "${value}" >> "${ENV_FILE}"
    return 0
  fi

  # Rewritten line by line rather than with sed, so a generated secret
  # containing / or & is written literally instead of being interpreted.
  local tmp
  tmp="$(mktemp)"
  while IFS= read -r line || [[ -n "${line}" ]]; do
    if [[ "${line}" == "${key}="* ]]; then
      printf '%s=%s\n' "${key}" "${value}" >> "${tmp}"
    else
      printf '%s\n' "${line}" >> "${tmp}"
    fi
  done < "${ENV_FILE}"

  # .env holds every credential in the stack, so preserve its 0600 mode by
  # overwriting in place instead of moving the temporary file over it.
  cat "${tmp}" > "${ENV_FILE}"
  rm -f "${tmp}"
}

# =============================================================================
# 1. Read the machine user's PAT
# =============================================================================
# Zitadel writes the PAT during first-instance setup, before it starts serving,
# so a healthy container normally already has one. The short wait only covers
# the filesystem lag of the bind mount.
for _ in $(seq 1 20); do
  [[ -s "${PAT_FILE}" ]] && break
  sleep 1
done

if [[ ! -s "${PAT_FILE}" ]]; then
  fail "Zitadel did not write a machine PAT to ${PAT_FILE}.
   It is only written while the *first* instance is created. If the Zitadel
   database already exists but the file is gone, reset the dev IAM state with
   ./scripts/down.sh --volumes and boot again."
fi
ZITADEL_PAT="$(tr -d '[:space:]' < "${PAT_FILE}")"
[[ -n "${ZITADEL_PAT}" ]] || fail "${PAT_FILE} is empty."

# A cheap authenticated call doubles as a PAT validity check.
api GET /auth/v1/users/me >/dev/null
ok "Authenticated against Zitadel as the bootstrap machine user"

# =============================================================================
# 2. Reconcile the Alfheim project
# =============================================================================
project_id=$(api POST /management/v1/projects/_search \
  "{\"queries\":[{\"nameQuery\":{\"name\":\"${PROJECT_NAME}\",\"method\":\"TEXT_QUERY_METHOD_EQUALS\"}}]}" \
  | json_field id)

if [[ -z "${project_id}" ]]; then
  info "Creating Zitadel project '${PROJECT_NAME}' …"
  project_id=$(api POST /management/v1/projects "{\"name\":\"${PROJECT_NAME}\"}" | json_field id)
  [[ -n "${project_id}" ]] || fail "Zitadel returned no project id."
  ok "Project '${PROJECT_NAME}' created (${project_id})"
else
  ok "Project '${PROJECT_NAME}' present (${project_id})"
fi

# =============================================================================
# 3. Reconcile the Grafana OIDC application
# =============================================================================
apps=$(api POST "/management/v1/projects/${project_id}/apps/_search" \
  "{\"queries\":[{\"nameQuery\":{\"name\":\"${GRAFANA_APP_NAME}\",\"method\":\"TEXT_QUERY_METHOD_EQUALS\"}}]}")
app_id=$(printf '%s' "${apps}" | json_field id)

# infrastructure/caddy/Caddyfile answers on the configured host, on the
# *.loegien.localhost dev aliases and on bare localhost, and Grafana derives
# its redirect URI from whichever one the browser used. Registering all of them
# is what keeps the login working regardless of the URL the developer opened.
grafana_hosts=("${APP_HOST}" "api.${APP_HOST}" \
  alfheim.loegien.localhost api.alfheim.loegien.localhost localhost)

json_array() {
  local first=true item
  printf '['
  for item in "$@"; do
    [[ "${first}" == "true" ]] || printf ','
    first=false
    printf '"%s"' "${item}"
  done
  printf ']'
}

redirect_uris=()
logout_uris=()
seen=""
for host in "${grafana_hosts[@]}"; do
  [[ "${seen}" == *"|${host}|"* ]] && continue
  seen="${seen}|${host}|"
  redirect_uris+=("http://${host}/grafana/login/generic_oauth")
  logout_uris+=("http://${host}/grafana/login")
done

grafana_redirects="$(json_array "${redirect_uris[@]}")"
grafana_logout="$(json_array "${logout_uris[@]}")"

oidc_config=$(cat <<JSON
{
  "redirectUris": ${grafana_redirects},
  "postLogoutRedirectUris": ${grafana_logout},
  "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
  "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE","OIDC_GRANT_TYPE_REFRESH_TOKEN"],
  "appType": "OIDC_APP_TYPE_WEB",
  "authMethodType": "OIDC_AUTH_METHOD_TYPE_BASIC",
  "version": "OIDC_VERSION_1_0",
  "devMode": true,
  "accessTokenType": "OIDC_TOKEN_TYPE_BEARER",
  "accessTokenRoleAssertion": true,
  "idTokenRoleAssertion": true,
  "idTokenUserinfoAssertion": true,
  "clockSkew": "1s"
}
JSON
)

client_id=""
client_secret=""

if [[ -z "${app_id}" ]]; then
  info "Registering the '${GRAFANA_APP_NAME}' OIDC application …"
  created=$(api POST "/management/v1/projects/${project_id}/apps/oidc" \
    "{\"name\":\"${GRAFANA_APP_NAME}\",$(printf '%s' "${oidc_config}" | sed -e '1s/^{//' -e '$s/}$//')}")
  client_id=$(printf '%s' "${created}" | json_field clientId)
  client_secret=$(printf '%s' "${created}" | json_field clientSecret)
  [[ -n "${client_id}" ]] || fail "Zitadel returned no clientId for '${GRAFANA_APP_NAME}'."
  ok "'${GRAFANA_APP_NAME}' OIDC application registered"
else
  ok "'${GRAFANA_APP_NAME}' OIDC application present (${app_id})"

  # Keep the redirect URIs in step with the configured dev domain. Zitadel
  # answers a no-op update with 400 COMMAND-1m88i ("No changes"), which for a
  # reconciling script is the success case.
  api PUT "/management/v1/projects/${project_id}/apps/${app_id}/oidc_config" \
    "${oidc_config}" "COMMAND-1m88i" >/dev/null

  client_id=$(printf '%s' "${apps}" | json_field clientId)
  known_secret="$(env_value GRAFANA_OIDC_CLIENT_SECRET)"
  known_id="$(env_value GRAFANA_OIDC_CLIENT_ID)"

  # Zitadel hands out a client secret once. It can only be recovered by
  # regenerating it, which is why .env — not Zitadel — is the source of truth
  # for the secret, and why a mismatch forces a regenerate.
  if [[ "${FORCE_SECRET}" == "true" || -z "${known_secret}" \
     || "${known_secret}" == "alfheim-grafana-secret" || "${known_id}" != "${client_id}" ]]; then
    info "Regenerating the '${GRAFANA_APP_NAME}' client secret …"
    client_secret=$(api POST \
      "/management/v1/projects/${project_id}/apps/${app_id}/oidc_config/_generate_client_secret" "{}" \
      | json_field clientSecret)
    [[ -n "${client_secret}" ]] || fail "Zitadel returned no clientSecret on regenerate."
  else
    client_secret="${known_secret}"
  fi
fi

# =============================================================================
# 4. Publish the credentials to .env for infrastructure/telemetry/compose.yml
# =============================================================================
set_env GRAFANA_OIDC_CLIENT_ID "${client_id}"
set_env GRAFANA_OIDC_CLIENT_SECRET "${client_secret}"
ok "Grafana OIDC credentials written to .env"
echo -e "  ${DIM}GRAFANA_OIDC_CLIENT_ID=${client_id}${RESET}"
