package apps

// CoreApps Registry defines Tier 1 Core Applications pre-built into Alfheim.
var CoreApps = []AppItem{
	{
		ID:           "pantry",
		Slug:         "pantry",
		Title:        "Digital Pantry",
		Name:         "Digital Pantry",
		Description:  "Manage household food inventory, recipes, and expiration dates.",
		Icon:         "kitchen",
		IconURL:      "kitchen",
		URL:          "/pantry",
		AppURL:       "/pantry",
		Category:     "internal",
		Tier:         TierCore,
		Status:       "active",
		DisplayOrder: 1,
	},
	{
		ID:           "shopping",
		Slug:         "shopping",
		Title:        "Smart Shopping",
		Name:         "Smart Shopping",
		Description:  "Automated shopping list generator and store price aggregator.",
		Icon:         "shopping_cart",
		IconURL:      "shopping_cart",
		URL:          "/shopping",
		AppURL:       "/shopping",
		Category:     "internal",
		Tier:         TierCore,
		Status:       "active",
		DisplayOrder: 2,
	},
	{
		ID:           "maintenance",
		Slug:         "maintenance",
		Title:        "Maintenance Hub",
		Name:         "Maintenance Hub",
		Description:  "Schedule device maintenance and home repairs.",
		Icon:         "build",
		IconURL:      "build",
		URL:          "/maintenance",
		AppURL:       "/maintenance",
		Category:     "internal",
		Tier:         TierCore,
		Status:       "active",
		DisplayOrder: 3,
	},
	{
		ID:           "chores",
		Slug:         "chores",
		Title:        "Chores Tracker",
		Name:         "Chores Tracker",
		Description:  "Haushaltsroutinen, Daily Resets & Streaks",
		Icon:         "cleaning_services",
		IconURL:      "cleaning_services",
		URL:          "/chores/de",
		AppURL:       "/chores/de",
		Category:     "internal",
		Tier:         TierCore,
		Status:       "active",
		DisplayOrder: 4,
	},
	{
		ID:           "workout",
		Slug:         "workout",
		Title:        "Workout Tracker",
		Name:         "Workout Tracker",
		Description:  "Gym splits, exercise tracking, volume analytics & streaks",
		Icon:         "fitness_center",
		IconURL:      "fitness_center",
		URL:          "/workout/de",
		AppURL:       "/workout/de",
		Category:     "internal",
		Tier:         TierCore,
		Status:       "active",
		DisplayOrder: 5,
	},
	{
		ID:           "todo",
		Slug:         "todo",
		Title:        "Task Tracker (TODO)",
		Name:         "Task Tracker (TODO)",
		Description:  "Manage personal and household tasks and reminders.",
		Icon:         "checklist",
		IconURL:      "checklist",
		URL:          "/under-construction?app=TODO",
		AppURL:       "/under-construction?app=TODO",
		Category:     "internal",
		Tier:         TierCore,
		Status:       "in_progress",
		DisplayOrder: 6,
	},
}
