name: Sonar-Cloud-Backend

on:
  push:
    branches: [master] # oder main
  pull_request:
    branches: [master]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # oder 'sulu'
          java-version: "21" # an Deine Java-Version anpassen

      - name: Build mit Maven
        run: mvn -B package # oder mvn verify
        working-directory: backend

      - name: SonarCloud Analyse
        run: mvn sonar:sonar -B
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
